# -*- coding: utf-8 -*-
"""Bath_prayertime_code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uoog3xevBJgX-IrNLKF8VAA-Zil3UOaV
"""

import pandas as pd
from datetime import date, timedelta
import os

# Get the current date
today = date.today()

# Get the current year
current_year = today.year

# Get the input file name without the extension
input_file_name = os.path.splitext(input('Enter the input xlsx file name without extension: '))[0]

# Add the current year to the input file name
output_file_name = f'{input_file_name}_{current_year}'

# Read the Excel file and skip the first row
df = pd.read_excel(f'{input_file_name}.xlsx', skiprows=1)

# Keep only the desired columns in the DataFrame
columns_to_keep = ['Fajr', 'Sunrise', 'Dhuhr', 'ʿAṣr', 'Maghrib', 'ʿIshā']
df = df[columns_to_keep]

try:
  # Convert the columns to datetime
  df = df.apply(pd.to_datetime, format='%H:%M:%S')

  # Remove the seconds from the values
  df = df.apply(lambda x: x.dt.strftime('%H:%M'))
except Exception as e:
  pass

timedifference = input('Is daylight saving British Summer Time (BST) on or off right now? Type 1 for on and 0 for off: ')

if timedifference == '1':
  # Subtract 1 hour from the HH values
  df = df.apply(lambda x: pd.to_datetime(x, format='%H:%M') - timedelta(hours=1))
else:
  df = df.apply(lambda x: pd.to_datetime(x, format='%H:%M'))

# Convert the columns back to strings
df = df.apply(lambda x: x.dt.strftime('%H:%M'))

# Insert a new empty column at the beginning
df.insert(0, 'Days', '')

if timedifference == '1':
  # Convert the DataFrame to a CSV file with the updated output file name
  df.to_csv(f'{output_file_name}_DST.csv', index=False)
else:
  df.to_csv(f'{output_file_name}_No_DST.csv', index=False)